version: 1.5.{build}
skip_tags: true
image: 
- Visual Studio 2017
configuration:
- Release
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
before_test:
- cmd: Dotnet test "Project2015To2017Tests\Project2015To2017Tests.csproj"
after_build:
- cmd: dotnet publish -f netcoreapp2.1 -c Release -o ./out/netcoreapp2.1 ./Project2015To2017.Console/Project2015To2017.Console.csproj
- cmd: dotnet publish -f net461 -c Release -o ./out/net461 ./Project2015To2017.Console/Project2015To2017.Console.csproj
- cmd: 7z a ./Project2015To2017/out/CSProj2015To2017.zip ./Project2015To2017.Console/out/*
- cmd: dotnet build /p:Pack=true -c Release ./Project2015To2017.Console/Project2015To2017.Console.csproj

artifacts:
  - path: ./Project2015To2017.Console/bin/$(configuration)/Project2015To2017.Cli.**.nupkg
    name: global-tool
  - path: ./Project2015To2017/out/CSProj2015To2017.zip
    name: out-zip
  - path: Project2015To2017\bin\$(configuration)\Project2015To2017.**.nupkg
    name: nupkg
    
deploy:
- provider: NuGet
  api_key:
    secure: i6ZaMLxF/Jbkh7SgDJuFIwpcrXl1BcNI5vd5Re33EEQV7PrZ71F6MpuIDF7glY/o
  skip_symbols: false
  artifact: nupkg
  
- provider: NuGet
  api_key:
    secure: +o0/XtevmiegEOJLY9u6bm57gbFvGT/0mraL78vBCtEjNkdjWkZEQGxiL//UP88S
  skip_symbols: false
  artifact: global-tool
    
- provider: GitHub  
  release: CSProj2015To2017-v$(APPVEYOR_BUILD_VERSION)
  description: 'Automatically built release v$(APPVEYOR_BUILD_VERSION).'
  auth_token:
    secure: "LYFGDMnT4oJLpCsZUkhL/oTnG3ZpQnsjaTc10DfTf/jbkXtzctRkXEu2ea3YnyqP" # your encrypted token from GitHub
  artifact: out-zip                # upload all NuGet packages to release assets
  draft: true
  prerelease: true
  on:
    branch: master        # deploy on tag push only
    
# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'